#!/usr/bin/env bash
# =============================================================================
# sync-migrations.sh — controlled copy of supabase/migrations into the
# kustomize tree (ADR-021 D3/F4').
#
# WHY: kustomize's load restrictor (LoadRestrictionsRootOnly, the default that
# `kubectl apply -k` enforces) forbids configMapGenerator `files:` outside the
# kustomization root, and rejects symlinks escaping it too. The source of truth
# stays in supabase/migrations/; this script regenerates the committed copy at
# k8s/base/db/migrations/ (sql files + kustomization.yaml with the explicit
# file list — generator `files:` does not glob).
#
# Usage:
#   scripts/k8s/sync-migrations.sh            # regenerate the copy
#   scripts/k8s/sync-migrations.sh --check    # CI gate: fail if out of sync
# =============================================================================
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SRC_DIR="${REPO_ROOT}/supabase/migrations"
DST_DIR="${REPO_ROOT}/k8s/base/db/migrations"

generate() {
  local target="$1"
  mkdir -p "${target}"
  local kustomization="${target}/kustomization.yaml"

  {
    echo "# GENERATED by scripts/k8s/sync-migrations.sh — DO NOT EDIT BY HAND."
    echo "# Source of truth: supabase/migrations/. Re-run the script after adding"
    echo "# a migration; CI enforces parity with --check."
    echo "apiVersion: kustomize.config.k8s.io/v1beta1"
    echo "kind: Kustomization"
    echo "configMapGenerator:"
    echo "  - name: hyperbrain-db-migrations"
    echo "    namespace: hyperbrain"
    echo "    files:"
    for f in "${SRC_DIR}"/*.sql; do
      echo "      - $(basename "${f}")"
    done
  } > "${kustomization}"

  cp "${SRC_DIR}"/*.sql "${target}/"
}

if [[ "${1:-}" == "--check" ]]; then
  tmp="$(mktemp -d)"
  trap 'rm -rf "${tmp}"' EXIT
  generate "${tmp}/migrations"
  if ! diff -r "${tmp}/migrations" "${DST_DIR}" >/dev/null 2>&1; then
    echo "ERROR: k8s/base/db/migrations is out of sync with supabase/migrations." >&2
    echo "Run scripts/k8s/sync-migrations.sh and commit the result." >&2
    diff -r "${tmp}/migrations" "${DST_DIR}" >&2 || true
    exit 1
  fi
  echo "OK: k8s/base/db/migrations is in sync ($(find "${SRC_DIR}" -maxdepth 1 -name '*.sql' | wc -l | tr -d ' ') migrations)."
else
  rm -rf "${DST_DIR}"
  generate "${DST_DIR}"
  echo "Regenerated ${DST_DIR} ($(find "${SRC_DIR}" -maxdepth 1 -name '*.sql' | wc -l | tr -d ' ') migrations)."
fi
