apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: hyperbrain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-container
          image: dacaitac/hyperbrain-be:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres-service
            - name: DB_USER
              value: user
            - name: DB_PASSWORD
              value: password
          envFrom:
            - secretRef:
                name: backend-secrets
