apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: hyperbrain
spec:
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      port: 1015
      targetPort: 1015
  type: ClusterIP